app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => ['auth','checkperms']], function () {


    Route::resource('/log', 'Log\ActionlogController');
    //Route::post('/log', 'Log\ActionlogController@index')->name('log.');

    //Route::get('/user/search', 'Auth\UserController@search');
    Route::post('/user/search', 'Auth\UserController@index')->name('user.search');

    Route::put('/user/info/{id}', 'Auth\UserController@updatePersonalInformation')->name('user.info');

    Route::put('/user/status/{id}', 'Auth\UserController@postStatus')->name('user.status');

    Route::resource('/user', 'Auth\UserController');
    Route::resource('/role', 'Auth\RoleController');
    Route::resource('/perm', 'Auth\PermissionController');


    Route::put('/incident/reassign/{id}', 'Incident\IncidentController@reassign')->name('incident.reassign');
    Route::get('/incident/assigned', 'Incident\IncidentController@assigned')->name('incident.assigned');
    Route::post('/incident/search', 'Incident\IncidentController@search')->name('incident.search');
    Route::put('/incident/progress/{id}', 'Incident\IncidentController@updateProgress')->name('incident.progress');

    Route::resource('/incident', 'Incident\IncidentController');
    Route::resource('/report', 'Report\ReportController');


    // Registration Routes...
    Route::get('auth/register', 'Auth\AuthController@getRegister')->name('auth.register');
    Route::post('auth/register', 'Auth\AuthController@postRegister')->name('auth.register');

});

Route::group(['middleware' => ['auth']], function() {
    Route::get('/', function () {
        //return view ('layouts.dashboard');
        return view('admin.index');
    });
    
});

Route::get('auth/login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('auth/login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('auth/logout', 'Auth\AuthController@getLogout')->name("auth.logout");

resources/views/perm/create.blade.php
@extends('admin.template')

@section('contentHeader')

    <h1>
        Permission Management
        <small>view permission information</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('perm.index') }}"><i class="fa fa-dashboard"></i> Permission</a></li>
        <li class="active">View permission</li>
    </ol>

@endsection

@section('content')

    @include('common.alert')



    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Add a New Permission</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="POST" action="{{ route('perm.store') }}">
                    {!! csrf_field() !!}

                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label>Name</label>

                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                            <label>Display name</label>
                            <input type="text" class="form-control" name="display_name" value="{{ old('display_name') }}">

                            @if ($errors->has('display_name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('display_name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label>Description</label>
                            <input type="text" class="form-control" name="description">

                            @if ($errors->has('description'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                            @endif
                        </div>


                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/perm/edit.blade.php
@extends('admin.template')

@section('contentHeader')

    <h1>
        Permission Management
        <small>edit permission information</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('perm.index') }}"><i class="fa fa-dashboard"></i> Permission</a></li>
        <li class="active">Edit permission</li>
    </ol>

@endsection

@section('content')

    @include('common.alert')



    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit a permission</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="POST" action="{{ route('perm.update',$perm->id ) }}">
                    {{ method_field('PUT') }}
                    {!! csrf_field() !!}

                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label>Name</label>

                            <input type="text" class="form-control" name="name" value="{{ old('name')?old('name'):$perm->name }}">

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                            <label>Display name</label>
                            <input type="text" class="form-control" name="display_name" value="{{ old('display_name')?old('display_name'):$perm->display_name }}">

                            @if ($errors->has('display_name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('display_name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label>Description</label>
                            <input type="text" class="form-control" name="description" value="{{ old('description')?old('description'):$perm->description }}">

                            @if ($errors->has('description'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('description')?:$perm->description  }}</strong>
                                    </span>
                            @endif
                        </div>



                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/perm/error.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: kwannokng
 * Date: 13/4/2017
 * Time: 10:33 PM
 */

resources/views/perm/view.blade.php
@extends('admin.template')

@section('contentHeader')

    <h1>
        Permission Management
        <small>view permission information</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('perm.index') }}"><i class="fa fa-dashboard"></i> Permission</a></li>
        <li class="active">View permission</li>
    </ol>

@endsection

@section('content')

    @include('common.alert')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        <a href="{{ route('perm.create') }}">
                            <button type="submit" class="btn btn-primary">Add Permission</button>
                        </a>
                    </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table id="roleTable" class="table  table-hover table-striped">

                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Display_name</th>
                                    <th>Linked with</th>
                                    <th>Description</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Action</th>

                                </tr>
                            </thead>
                            <tbody>

                                @foreach($perms as $perm)
                                    <tr>
                                        <td>{{ $perm->id }}</td>
                                        <td>{{ $perm->name }}</td>
                                        <td>{{ $perm->display_name }}</td>
                                        <td>
                                            @foreach($perm->roles as $role)
                                                {{ $role->name }}
                                            @endforeach
                                        </td>
                                        <td>{{ $perm->description }}</td>
                                        <td>{{ $perm->created_at }}</td>
                                        <td>{{ $perm->updated_at }}</td>
                                        <td><button type="button" class="btn btn-warning" onclick="javascript:location.href='/perm/{{ $perm->id }}'">Detail</button></td>
                                    </tr>
                                @endforeach

                            </tbody>

                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>


@endsection

@section('contentJS')
<script>

    $(function () {

        $('#roleTable').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    });


</script>

@endsection