app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => ['auth','checkperms']], function () {


    Route::resource('/log', 'Log\ActionlogController');
    //Route::post('/log', 'Log\ActionlogController@index')->name('log.');

    //Route::get('/user/search', 'Auth\UserController@search');
    Route::post('/user/search', 'Auth\UserController@index')->name('user.search');

    Route::put('/user/info/{id}', 'Auth\UserController@updatePersonalInformation')->name('user.info');

    Route::put('/user/status/{id}', 'Auth\UserController@postStatus')->name('user.status');

    Route::resource('/user', 'Auth\UserController');
    Route::resource('/role', 'Auth\RoleController');
    Route::resource('/perm', 'Auth\PermissionController');


    Route::put('/incident/reassign/{id}', 'Incident\IncidentController@reassign')->name('incident.reassign');
    Route::get('/incident/assigned', 'Incident\IncidentController@assigned')->name('incident.assigned');
    Route::post('/incident/search', 'Incident\IncidentController@search')->name('incident.search');
    Route::put('/incident/progress/{id}', 'Incident\IncidentController@updateProgress')->name('incident.progress');

    Route::resource('/incident', 'Incident\IncidentController');
    Route::resource('/report', 'Report\ReportController');


    // Registration Routes...
    Route::get('auth/register', 'Auth\AuthController@getRegister')->name('auth.register');
    Route::post('auth/register', 'Auth\AuthController@postRegister')->name('auth.register');

});

Route::group(['middleware' => ['auth']], function() {
    Route::get('/', function () {
        //return view ('layouts.dashboard');
        return view('admin.index');
    });
    
});

Route::get('auth/login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('auth/login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('auth/logout', 'Auth\AuthController@getLogout')->name("auth.logout");

resources/views/admin/footer.blade.php
<!--
<footer class="main-footer">
    <!-- To the right
    <div class="pull-right hidden-xs">
        Anything you want
    </div>
    <!-- Default to the left
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
</footer>-->

resources/views/admin/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="/" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>D</b>T</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>D</b>Team</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">{{ count($stillValidIncidents[0]->calendar) }}</span>
                    </a>
                    <ul class="dropdown-menu">


                        <li class="header">You have {{ count($stillValidIncidents[0]->calendar) }} messages</li>


                        @foreach($stillValidIncidents as $user)
                            @foreach($user->calendar as $calendar)

                        <!-- <li class="header">You have 4 messages</li>-->
                                <li>
                                    <!-- inner menu: contains the messages -->
                                    <ul class="menu">
                                        <li><!-- start message -->
                                            <a href="/incident/{{ $calendar->incident->id }}">
                                                <div class="pull-left">
                                                    <!-- User Image -->
                                                    <img src="http://placehold.it/160x160/00a65a/ffffff/&text={{ strtoupper(substr($calendar->incident->user->name, 0, 1)) }}" class="img-circle" alt="User Image">
                                                </div>
                                                <!-- Message title and timestamp -->
                                                <h4>
                                                    {{  $calendar->incident->title }}
                                                    <small><i class="fa fa-clock-o"></i>
                                                        @if ( isset ($calendar->incident->progress[0]))

                                                            {{  explode(" ",$calendar->incident->progress[0]->pivot->updated_at)[0] }}
                                                        @endif</small>
                                                </h4>
                                                <!-- The message -->
                                                <p>{{ $calendar->incident->progress[0]->description }}</p>
                                            </a>
                                        </li>
                                        <!-- end message -->
                                    </ul>
                                    <!-- /.menu -->
                                </li>
                                <li class="footer"><a href="#">See All Messages</a></li>
                             @endforeach
                        @endforeach
                    </ul>
                </li>
                <!-- /.messages-menu -->

                <!-- Notifications Menu -->
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="http://placehold.it/160x160/00a65a/ffffff/&text={{ strtoupper(substr(Auth::user()->name, 0, 1)) }}" class="user-image" alt="User Image">

                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="http://placehold.it/160x160/00a65a/ffffff/&text={{ strtoupper(substr(Auth::user()->name, 0, 1)) }}" class="img-circle" alt="User Image">

                            <p>
                                {{ Auth::user()->name ."-" . Auth::user()->jobTitle  }}
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!--
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                            <!-- /.row -
                        </li>-->
                        <!-- Menu Footer-->
                        <li class="user-footer">

                            <div class="pull-right">
                                <a href="{{ route('auth.logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/index.blade.php
@extends('admin.template')

@section('contentHeader')

    <h1>
        Dashboard
        <small>welcome to use it</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    </ol>

@endsection

@section('content')

    @include('common.alert')


@endsection

resources/views/admin/menu.blade.php
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">

                <?php /*<img src="http://placehold.it/160x160/00a65a/ffffff/&text={{ Auth::user()->name[0] }}" class="img-circle" alt="User Image">*/ ?>
                <img src="http://placehold.it/160x160/00a65a/ffffff/&text={{ strtoupper(substr(Auth::user()->name, 0, 1)) }}"
                     class="img-circle" alt="User Image">

            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <!--
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>-->
        <!-- /.search form -->

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">Main Information</li>
            <!-- Optionally, you can add icons to the links -->

            @role('admin')
            <li class="treeview">
                <a href="#"><i class="fa fa-users"></i> <span>User</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('user.index')  }}"><i class="fa fa-user"></i>User</a></li>
                    <li><a href="{{ route('role.index')  }}"><i class="fa fa-user"></i>Role</a></li>
                    <li><a href="{{ route('perm.index')  }}"><i class="fa fa-user"></i>Pemission</a></li>
                    <li><a href="{{ route('log.index')  }}"><i class="fa fa-users"></i>Activity Log</a></li>
                </ul>
            </li>
            @endrole('admin')
            {{--
            @role('admin')
            <li class="treeview">
                <a href="#"><i class="fa fa-toggle-on"></i> <span>Distribute</span>
                                    <span class="pull-right-container">
                                      <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-arrows-v"></i>Method Selection</a></li>
                </ul>
            </li>
            @endrole
            --}}

            @role(['admin', 'front-end','developer'])
            <li class="treeview">
                <a href="#"><i class="fa fa-ticket"></i> <span>Incident</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('incident.create')  }}"><i class="fa fa-circle-o"></i>Create</a></li>
                    <li><a href="{{ route('incident.index')  }}"><i class="fa fa-circle-o"></i>View</a></li>
                    <li><a href="{{ route('incident.assigned')  }}"><i class="fa fa-circle-o"></i>Assigned</a></li>
                </ul>
            </li>
            @endrole

            @role(['admin','analysis'])
            <li class="">
                <a href="{{ route('report.index')  }}">
                    <i class="fa fa-line-chart"></i>
                    <span>Report</span>
                </a>
            </li>
            @endrole

        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->

</aside>

@section('menuJS')
    <script>
        // Set active state on menu element
        var current_url = "{{ url(Route::current()->getUri()) }}";
        $("ul.sidebar-menu li a").each(function () {
            if ($(this).attr('href').startsWith(current_url) || current_url.startsWith($(this).attr('href'))) {
                $(this).parents('li').addClass('active');
            }
        });
    </script>
@endsection

resources/views/admin/rightbar.blade.php
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">

            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Receive Incident Progress</h3>
            <ul class="control-sidebar-menu">

                @foreach($stillValidIncidents as $user)
                    @foreach($user->calendar as $calendar)
                        <li>
                            <a href="/incident/{{ $calendar->incident->id }}">
                                <h4 class="control-sidebar-subheading">
                                       {{  $calendar->incident->title }}
                                <span class="pull-right-container">
                                  <span class="label label-danger pull-right">
                                          @if ( isset ($calendar->incident->progress[0]))
                                          {{
                                          Config::get('constant.calendar.setting.'.
                                          ($calendar->incident->progress[0]->id ).
                                          '.percentage')
                                          }}
                                          @endif

                                  </span>
                                </span>
                                </h4>

                                <div class="progress progress-xxs">

                                    @if ( isset ($calendar->incident->progress[0]))
                                        <div class="progress-bar progress-bar-danger" style="width: {{
                                        Config::get('constant.calendar.setting.'.
                                        ($calendar->incident->progress[0]->id ).
                                        '.percentage')
                                        }}"></div>


                                    @endif

                                </div>
                            </a>
                        </li>
                    @endforeach

                @endforeach

            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <h3 class="control-sidebar-heading">Assigned Incident Progress</h3>
            <ul class="control-sidebar-menu">

                @foreach($stillValidIncidentsAssign as $users)
                    @foreach($users->incident as $incident)
                        <li>
                            <a href="/incident/{{ $incident->calendar->id }}">
                                <h4 class="control-sidebar-subheading">
                                    {{  $incident->calendar->title }}
                                    <span class="pull-right-container">
                                  <span class="label label-danger pull-right">
                                          @if ( isset ($incident->calendar->progress[0]))
                                          {{
                                          Config::get('constant.calendar.setting.'.
                                          ($incident->calendar->progress[0]->id ).
                                          '.percentage')
                                          }}
                                      @endif

                                  </span>
                                </span>
                                </h4>

                                <div class="progress progress-xxs">

                                    @if ( isset ($incident->calendar->progress[0]))
                                        <div class="progress-bar progress-bar-danger" style="width: {{
                                        Config::get('constant.calendar.setting.'.
                                        ($incident->calendar->progress[0]->id ).
                                        '.percentage')
                                        }}"></div>


                                    @endif

                                </div>
                            </a>
                        </li>
                    @endforeach

                @endforeach

            </ul>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<div class="control-sidebar-bg"></div>

resources/views/admin/template.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>DTeam</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <!-- Font Awesome -->
    <!-- all css -->

    <!-- all css -->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="/assets/css/all.css">

    <link rel="stylesheet" href="/assets/css/view_role.css">

    @yield('stylecss')

    <!-- Theme style -->
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    @include('admin.header')
    <!-- Left side column. contains the logo and sidebar -->
    @include('admin.menu')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            @yield('contentHeader')
        </section>

        <!-- Main content -->
        <section class="content">
            @yield('content')
            <!-- Your Page Content Here -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    @include('admin.footer')
    <!-- Control Sidebar -->
    @include('admin.rightbar')
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
</div>
<!-- ./wrapper -->
<!-- REQUIRED JS SCRIPTS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="/assets/js/admin.js" type="text/javascript"></script>
<script src="/assets/js/general.js" type="text/javascript"></script>
@yield('menuJS')
@yield('contentJS')

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
</body>
</html>