app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => ['auth','checkperms']], function () {


    Route::resource('/log', 'Log\ActionlogController');
    //Route::post('/log', 'Log\ActionlogController@index')->name('log.');

    //Route::get('/user/search', 'Auth\UserController@search');
    Route::post('/user/search', 'Auth\UserController@index')->name('user.search');

    Route::put('/user/info/{id}', 'Auth\UserController@updatePersonalInformation')->name('user.info');

    Route::put('/user/status/{id}', 'Auth\UserController@postStatus')->name('user.status');

    Route::resource('/user', 'Auth\UserController');
    Route::resource('/role', 'Auth\RoleController');
    Route::resource('/perm', 'Auth\PermissionController');


    Route::put('/incident/reassign/{id}', 'Incident\IncidentController@reassign')->name('incident.reassign');
    Route::get('/incident/assigned', 'Incident\IncidentController@assigned')->name('incident.assigned');
    Route::post('/incident/search', 'Incident\IncidentController@search')->name('incident.search');
    Route::put('/incident/progress/{id}', 'Incident\IncidentController@updateProgress')->name('incident.progress');

    Route::resource('/incident', 'Incident\IncidentController');
    Route::resource('/report', 'Report\ReportController');


    // Registration Routes...
    Route::get('auth/register', 'Auth\AuthController@getRegister')->name('auth.register');
    Route::post('auth/register', 'Auth\AuthController@postRegister')->name('auth.register');

});

Route::group(['middleware' => ['auth']], function() {
    Route::get('/', function () {
        //return view ('layouts.dashboard');
        return view('admin.index');
    });
    
});

Route::get('auth/login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('auth/login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('auth/logout', 'Auth\AuthController@getLogout')->name("auth.logout");

app/Role.php
<?php
//test
namespace App;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
    protected $fillable = ['name', 'display_name', 'description'];


}

resources/views/role/create.blade.php
@extends('admin.template')

@section('contentHeader')

    <h1>
        Role Management
        <small>view role information</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('role.index') }}"><i class="fa fa-dashboard"></i> Role</a></li>
        <li class="active">View role</li>
    </ol>

@endsection

@section('content')

    @include('common.alert')



    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Add a New Role</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="POST" action="{{ route('role.store') }}">
                    {!! csrf_field() !!}

                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label>Name</label>

                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                            <label>Display name</label>
                            <input type="text" class="form-control" name="display_name" value="{{ old('display_name') }}">

                            @if ($errors->has('display_name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('display_name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label>Description</label>
                            <input type="text" class="form-control" name="description">

                            @if ($errors->has('description'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                            @endif
                        </div>

                        <div class="row form-group{{ $errors->has('perms') ? ' has-error' : '' }}">
                            <div class="col-xs-12">
                                <label>Permission</label>

                                @if ($errors->has('perms'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('perms') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="hidden_fields_primary" data-name = "role"></div>

                            @foreach($perms as $perm)
                                <div class="col-sm-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" value="{{ $perm->id }}" name="perms[]"  data-id="{{$perm->id}}" class="secondary_list"> {{ $perm->name }}
                                        </label>
                                    </div>
                                </div>
                            @endforeach
                        </div>


                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/role/edit.blade.php
@extends('admin.template')

@section('contentHeader')

    <h1>
        Role Management
        <small>edit role information</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('role.index') }}"><i class="fa fa-dashboard"></i> Role</a></li>
        <li class="active">Edit role</li>
    </ol>

@endsection

@section('content')

    @include('common.alert')



    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit a role</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="POST" action="{{ route('role.update',$role->id ) }}">
                    {{ method_field('PUT') }}
                    {!! csrf_field() !!}

                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label>Name</label>

                            <input type="text" class="form-control" name="name" value="{{ old('name')?old('name'):$role->name }}">

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                            <label>Display name</label>
                            <input type="text" class="form-control" name="display_name" value="{{ old('display_name')?old('display_name'):$role->display_name }}">

                            @if ($errors->has('display_name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('display_name') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label>Description</label>
                            <input type="text" class="form-control" name="description" value="{{ old('description')?old('description'):$role->description }}">

                            @if ($errors->has('description'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('description')?:$role->description  }}</strong>
                                    </span>
                            @endif
                        </div>

                        <div class="row form-group{{ $errors->has('perms') ? ' has-error' : '' }}">
                            <div class="col-xs-12">
                                <label>Permission</label>

                                @if ($errors->has('perms'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('perms') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="hidden_fields_primary" data-name = "role"></div>

                            @foreach($perms as $perm)
                                <div class="col-sm-4">
                                    <div class="checkbox">
                                        <label>

                                            <input type="checkbox" value="{{ $perm->id }}" name="perms[]"  data-id="{{$perm->id}}" class="secondary_list"> {{ $perm->name }}
                                        </label>
                                    </div>
                                </div>
                            @endforeach
                        </div>


                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('contentJS')
    <script>
        $(document).ready(function(){
            var rolePermission = JSON.parse('{!! $rolePermission !!}')


            $.each(rolePermission, function(i,v){
                console.log("rolePermission : " + v);
                $('.secondary_list[value="'+v+'"]').prop('checked', true);
            });

        })


    </script>

@endsection

resources/views/role/view.blade.php
@extends('admin.template')

@section('contentHeader')

    <h1>
        Role Management
        <small>view role information</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="{{ route('role.index') }}"><i class="fa fa-dashboard"></i> Role</a></li>
        <li class="active">View role</li>
    </ol>

@endsection

@section('content')

    @include('common.alert')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        <a href="{{ route('role.create') }}">
                            <button type="submit" class="btn btn-primary">Add Role</button>
                        </a>
                    </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table id="roleTable" class="table  table-hover table-striped">

                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Display_name</th>
                                    <th>Description</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Action</th>
                                    <th>Remove</th>

                                </tr>
                            </thead>
                            <tbody>

                                @foreach($roles as $role)
                                    <tr>
                                        <td>{{ $role->id }}</td>
                                        <td>{{ $role->name }}</td>
                                        <td>{{ $role->display_name }}</td>
                                        <td>{{ $role->description }}</td>
                                        <td>{{ $role->created_at }}</td>
                                        <td>{{ $role->updated_at }}</td>
                                        <td><button type="button" class="btn btn-warning" onclick="javascript:location.href='/role/{{ $role->id }}'">Detail</button></td>
                                        <td>
                                            <form method="POST" action="{{ route('role.destroy', $role->id) }}">
                                                {!! csrf_field() !!}
                                                {{ method_field('DELETE') }}
                                                <button type="submit" class="btn btn-danger">Remove</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>

                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>


@endsection

@section('contentJS')
<script>

    $(function () {


        $('#roleTable').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    });


</script>

@endsection